#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class DiscoveryJobNIO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {

            'snmpStatus': 'str',


            'cliStatus': 'str',


            'pingStatus': 'str',


            'inventoryReachabilityStatus': 'str',


            'startTime': 'str',


            'endTime': 'str',


            'jobStatus': 'str',


            'inventoryCollectionStatus': 'str',


            'taskId': 'str',


            'ipAddress': 'str',


            'discoveryStatus': 'str',


            'name': 'str',


            'id': 'str',


            'attributeInfo': 'object'

        }

        self.attributeMap = {

            'snmpStatus': 'snmpStatus',

            'cliStatus': 'cliStatus',

            'pingStatus': 'pingStatus',

            'inventoryReachabilityStatus': 'inventoryReachabilityStatus',

            'startTime': 'startTime',

            'endTime': 'endTime',

            'jobStatus': 'jobStatus',

            'inventoryCollectionStatus': 'inventoryCollectionStatus',

            'taskId': 'taskId',

            'ipAddress': 'ipAddress',

            'discoveryStatus': 'discoveryStatus',

            'name': 'name',

            'id': 'id',

            'attributeInfo': 'attributeInfo'

        }


        #SNMP status for the IP during this job run

        self.snmpStatus = None # str

        #CLI status for the IP during this job run

        self.cliStatus = None # str

        #Ping status for the IP during this job run

        self.pingStatus = None # str

        #Last known reachabilty status of the device

        self.inventoryReachabilityStatus = None # str

        #Discovery job start time

        self.startTime = None # str


        self.endTime = None # str


        self.jobStatus = None # str

        #Last known inventory collection status of the device

        self.inventoryCollectionStatus = None # str

        #Discovery job task id

        self.taskId = None # str

        #IP Address

        self.ipAddress = None # str

        #Discovery status for the IP

        self.discoveryStatus = None # str

        #Discovery job name

        self.name = None # str


        self.id = None # str


        self.attributeInfo = None # object

