#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class GlobalCredentialDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'comments': 'str',
            
            
            'description': 'str',
            
            
            'credentialType': 'str',
            
            
            'instanceUuid': 'str',
            
            
            'id': 'str',

            'username': 'str' # added this manually
            
        }

        self.attributeMap = {
            
            'comments': 'comments',
            
            'description': 'description',
            
            'credentialType': 'credentialType',
            
            'instanceUuid': 'instanceUuid',
            
            'id': 'id',

            'username': 'username' # added this manually
            
        }       

        #Added line 66-69 manually
        #CLI username or SNMP user name

        self.username = None # str

        #Comments to identify the credential
        
        self.comments = None # str
        
        #Description of the credential
        
        self.description = None # str
        
        #Credential type to identify the application that uses the credential
        
        self.credentialType = None # str
        
        
        self.instanceUuid = None # str
        
        
        self.id = None # str
        
