#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class InventoryDeviceInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'snmpAuthPassphrase': 'str',
            
            
            'snmpAuthProtocol': 'str',
            
            
            'snmpRetry': 'int',
            
            
            'snmpPrivPassphrase': 'str',
            
            
            'snmpPrivProtocol': 'str',
            
            
            'snmpROCommunity': 'str',
            
            
            'snmpRWCommunity': 'str',
            
            
            'extendedDiscoveryInfo': 'str',
            
            
            'cliTransport': 'str',
            
            
            'enablePassword': 'str',
            
            
            'serialNumber': 'str',
            
            
            'snmpVersion': 'str',
            
            
            'userName': 'str',
            
            
            'password': 'str',
            
            
            'ipAddress': 'list[str]',
            
            
            'snmpMode': 'str',
            
            
            'snmpTimeout': 'int',
            
            
            'snmpUserName': 'str'
            
        }

        self.attributeMap = {
            
            'snmpAuthPassphrase': 'snmpAuthPassphrase',
            
            'snmpAuthProtocol': 'snmpAuthProtocol',
            
            'snmpRetry': 'snmpRetry',
            
            'snmpPrivPassphrase': 'snmpPrivPassphrase',
            
            'snmpPrivProtocol': 'snmpPrivProtocol',
            
            'snmpROCommunity': 'snmpROCommunity',
            
            'snmpRWCommunity': 'snmpRWCommunity',
            
            'extendedDiscoveryInfo': 'extendedDiscoveryInfo',
            
            'cliTransport': 'cliTransport',
            
            'enablePassword': 'enablePassword',
            
            'serialNumber': 'serialNumber',
            
            'snmpVersion': 'snmpVersion',
            
            'userName': 'userName',
            
            'password': 'password',
            
            'ipAddress': 'ipAddress',
            
            'snmpMode': 'snmpMode',
            
            'snmpTimeout': 'snmpTimeout',
            
            'snmpUserName': 'snmpUserName'
            
        }       

        
        #SNMPV3 auth passphrase
        
        self.snmpAuthPassphrase = None # str
        
        #SNMPV3 auth protocol. Supported values: sha, md5
        
        self.snmpAuthProtocol = None # str
        
        #SNMP retry count. Max value supported is 3
        
        self.snmpRetry = None # int
        
        #SNMPV3 priv passphrase
        
        self.snmpPrivPassphrase = None # str
        
        #SNMPV3 priv protocol. Supported values: des, aes
        
        self.snmpPrivProtocol = None # str
        
        #SNMP RO community
        
        self.snmpROCommunity = None # str
        
        #SNMP RW community
        
        self.snmpRWCommunity = None # str
        
        
        self.extendedDiscoveryInfo = None # str
        
        #CLI transport. Supported values: telnet, ssh2
        
        self.cliTransport = None # str
        
        #CLI enable password
        
        self.enablePassword = None # str
        
        
        self.serialNumber = None # str
        
        #SNMP version. Values supported: 2c, 3. Default is 2c
        
        self.snmpVersion = None # str
        
        #CLI user name
        
        self.userName = None # str
        
        #CLI password
        
        self.password = None # str
        
        #IP Address of the device
        
        self.ipAddress = None # list[str]
        
        #SNMPV3 mode. Supported values: noAuthnoPriv, authNoPriv, authPriv
        
        self.snmpMode = None # str
        
        #SNMP timeout in seconds
        
        self.snmpTimeout = None # int
        
        #SNMPV3 user name
        
        self.snmpUserName = None # str
        
