#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class NetworkDeviceNIO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'ingressQueueConfig': 'str',
            
            
            'authModelId': 'str',
            
            
            'duplicateDeviceId': 'str',
            
            
            'anchorWlcForAp': 'str',
            
            
            'wlcApDeviceStatus': 'str',
            
            
            'inventoryReachabilityStatus': 'str',
            
            
            'serialNumber': 'str',
            
            
            'portRange': 'str',
            
            
            'type': 'str',
            
            
            'hostname': 'str',
            
            
            'inventoryCollectionStatus': 'str',
            
            
            'location': 'str',
            
            
            'role': 'str',
            
            
            'softwareVersion': 'str',
            
            
            'vendor': 'str',
            
            
            'errorDescription': 'str',
            
            
            'imageName': 'str',
            
            
            'lastUpdated': 'str',
            
            
            'upTime': 'str',
            
            
            'errorCode': 'str',
            
            
            'locationName': 'str',
            
            
            'tagCount': 'int',
            
            
            'id': 'str',
            
            
            'macAddress': 'str',
            
            
            'tag': 'str',
            
            
            'avgUpdateFrequency': 'int',
            
            
            'roleSource': 'str',
            
            
            'numUpdates': 'int',
            
            
            'managementIpAddress': 'str',
            
            
            'memorySize': 'str',
            
            
            'platformId': 'str',
            
            
            'reachabilityFailureReason': 'str',
            
            
            'reachabilityStatus': 'str',
            
            
            'snmpContact': 'str',
            
            
            'snmpLocation': 'str',
            
            
            'bootDateTime': 'DateTime',
            
            
            'family': 'str',
            
            
            'interfaceCount': 'str',
            
            
            'lineCardCount': 'str',
            
            
            'lineCardId': 'str',
            
            
            'qosStatus': 'str',
            
            
            'pingStatus': 'str',
            
            
            'snmpStatus': 'str',
            
            
            'cliStatus': 'str'
            
        }

        self.attributeMap = {
            
            'ingressQueueConfig': 'ingressQueueConfig',
            
            'authModelId': 'authModelId',
            
            'duplicateDeviceId': 'duplicateDeviceId',
            
            'anchorWlcForAp': 'anchorWlcForAp',
            
            'wlcApDeviceStatus': 'wlcApDeviceStatus',
            
            'inventoryReachabilityStatus': 'inventoryReachabilityStatus',
            
            'serialNumber': 'serialNumber',
            
            'portRange': 'portRange',
            
            'type': 'type',
            
            'hostname': 'hostname',
            
            'inventoryCollectionStatus': 'inventoryCollectionStatus',
            
            'location': 'location',
            
            'role': 'role',
            
            'softwareVersion': 'softwareVersion',
            
            'vendor': 'vendor',
            
            'errorDescription': 'errorDescription',
            
            'imageName': 'imageName',
            
            'lastUpdated': 'lastUpdated',
            
            'upTime': 'upTime',
            
            'errorCode': 'errorCode',
            
            'locationName': 'locationName',
            
            'tagCount': 'tagCount',
            
            'id': 'id',
            
            'macAddress': 'macAddress',
            
            'tag': 'tag',
            
            'avgUpdateFrequency': 'avgUpdateFrequency',
            
            'roleSource': 'roleSource',
            
            'numUpdates': 'numUpdates',
            
            'managementIpAddress': 'managementIpAddress',
            
            'memorySize': 'memorySize',
            
            'platformId': 'platformId',
            
            'reachabilityFailureReason': 'reachabilityFailureReason',
            
            'reachabilityStatus': 'reachabilityStatus',
            
            'snmpContact': 'snmpContact',
            
            'snmpLocation': 'snmpLocation',
            
            'bootDateTime': 'bootDateTime',
            
            'family': 'family',
            
            'interfaceCount': 'interfaceCount',
            
            'lineCardCount': 'lineCardCount',
            
            'lineCardId': 'lineCardId',
            
            'qosStatus': 'qosStatus',
            
            'pingStatus': 'pingStatus',
            
            'snmpStatus': 'snmpStatus',
            
            'cliStatus': 'cliStatus'
            
        }       

        
        #Ingress queue config on device
        
        self.ingressQueueConfig = None # str
        
        #Authentication model Id on device
        
        self.authModelId = None # str
        
        #Identifier of the duplicate ip of the same device discovered
        
        self.duplicateDeviceId = None # str
        
        #Connected WLC device for AP
        
        self.anchorWlcForAp = None # str
        
        #Collection status of AP devices
        
        self.wlcApDeviceStatus = None # str
        
        #Inventory reachablity status
        
        self.inventoryReachabilityStatus = None # str
        
        #Serial number of device
        
        self.serialNumber = None # str
        
        #Range of ports on device
        
        self.portRange = None # str
        
        #Type of device as switch, router, wireless lan controller, accesspoints
        
        self.type = None # str
        
        #Device name
        
        self.hostname = None # str
        
        #Inventory status
        
        self.inventoryCollectionStatus = None # str
        
        #Location ID that is associated with the device
        
        self.location = None # str
        
        #Role of device as access, distribution, border router, core
        
        self.role = None # str
        
        #Software version on the device
        
        self.softwareVersion = None # str
        
        #Vendor information of the device
        
        self.vendor = None # str
        
        #Inventory status description
        
        self.errorDescription = None # str
        
        #Image details on the device
        
        self.imageName = None # str
        
        #Time when the network device info last got updated
        
        self.lastUpdated = None # str
        
        #Time that shows for how long the device has been up
        
        self.upTime = None # str
        
        #Inventory status error code
        
        self.errorCode = None # str
        
        #Name of the associated location
        
        self.locationName = None # str
        
        #Number of tags associated with the device
        
        self.tagCount = None # int
        
        #Unique identifier of network device
        
        self.id = None # str
        
        #MAC address of device
        
        self.macAddress = None # str
        
        #Tag ID that is associated with the device
        
        self.tag = None # str
        
        #Frequency in which interface info gets updated
        
        self.avgUpdateFrequency = None # int
        
        #Role source as manual / auto
        
        self.roleSource = None # str
        
        #Number of time network-device info got updated
        
        self.numUpdates = None # int
        
        #IP address of the device
        
        self.managementIpAddress = None # str
        
        #Processor memory size
        
        self.memorySize = None # str
        
        #Platform ID of device
        
        self.platformId = None # str
        
        #Failure reason for unreachable devices
        
        self.reachabilityFailureReason = None # str
        
        #Device reachability status as Reachable / Unreachable
        
        self.reachabilityStatus = None # str
        
        #SNMP contact on device
        
        self.snmpContact = None # str
        
        #SNMP location on device
        
        self.snmpLocation = None # str
        
        #Device boot time
        
        self.bootDateTime = None # DateTime
        
        #Family of device as switch, router, wireless lan controller, accesspoints
        
        self.family = None # str
        
        #Number of interfaces on the device
        
        self.interfaceCount = None # str
        
        #Number of linecards on the device
        
        self.lineCardCount = None # str
        
        #IDs of linecards of the device
        
        self.lineCardId = None # str
        
        #Qos status on device
        
        self.qosStatus = None # str
        
        #Ping status at the time of discovery
        
        self.pingStatus = None # str
        
        #SNMP status at the time of discovery
        
        self.snmpStatus = None # str
        
        #CLI status at the time of discovery
        
        self.cliStatus = None # str
        
