#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class RawCliInfoNIO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'inventory': 'str',
            
            
            'ipIntfBrief': 'str',
            
            
            'intfDescription': 'str',
            
            
            'macAddressTable': 'str',
            
            
            'healthMonitor': 'str',
            
            
            'snmp': 'str',
            
            
            'version': 'str',
            
            
            'id': 'str',
            
            
            'runningConfig': 'str',
            
            
            'cdpNeighbors': 'str',
            
            
            'attributeInfo': 'object'
            
        }

        self.attributeMap = {
            
            'inventory': 'inventory',
            
            'ipIntfBrief': 'ipIntfBrief',
            
            'intfDescription': 'intfDescription',
            
            'macAddressTable': 'macAddressTable',
            
            'healthMonitor': 'healthMonitor',
            
            'snmp': 'snmp',
            
            'version': 'version',
            
            'id': 'id',
            
            'runningConfig': 'runningConfig',
            
            'cdpNeighbors': 'cdpNeighbors',
            
            'attributeInfo': 'attributeInfo'
            
        }       

        
        #Inventory configuration info of the device
        
        self.inventory = None # str
        
        #IP interface brief configuration info of the device
        
        self.ipIntfBrief = None # str
        
        #Interface configuration info of the device
        
        self.intfDescription = None # str
        
        #MAC address configuration info of the device
        
        self.macAddressTable = None # str
        
        #Health monitor configuration info of the device
        
        self.healthMonitor = None # str
        
        #SNMP configuration info of the device
        
        self.snmp = None # str
        
        #Version configuration info of the device
        
        self.version = None # str
        
        #Unique identifier for config
        
        self.id = None # str
        
        #Running-config of the device
        
        self.runningConfig = None # str
        
        #CDP configuration info of the device
        
        self.cdpNeighbors = None # str
        
        
        self.attributeInfo = None # object
        
