#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class TagNIO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'id': 'str',
            
            
            'lastUpdated': 'str',
            
            
            'locationId': 'str',
            
            
            'linkId': 'str',
            
            
            'tag': 'str',
            
            
            'interfaceId': 'str',
            
            
            'networkDeviceId': 'str'
            
        }

        self.attributeMap = {
            
            'id': 'id',
            
            'lastUpdated': 'lastUpdated',
            
            'locationId': 'locationId',
            
            'linkId': 'linkId',
            
            'tag': 'tag',
            
            'interfaceId': 'interfaceId',
            
            'networkDeviceId': 'networkDeviceId'
            
        }       

        
        #Unique identifier of tag
        
        self.id = None # str
        
        #Time when the device interface info last got updated
        
        self.lastUpdated = None # str
        
        #Unique identifier of location
        
        self.locationId = None # str
        
        #Unique identifier of link
        
        self.linkId = None # str
        
        #Tag Id
        
        self.tag = None # str
        
        #Unique identifier of the interface
        
        self.interfaceId = None # str
        
        #Unique identifier of device
        
        self.networkDeviceId = None # str
        
