#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class ZtdSmartAccountDevice(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'serialNumber': 'str',
            
            
            'stateDisplay': 'str',
            
            
            'id': 'str',
            
            
            'platformId': 'str',
            
            
            'macAddress': 'str',
            
            
            'smartAccountDeviceId': 'str',
            
            
            'pnpSmartAccountId': 'str',
            
            
            'pnpManaged': 'bool',
            
            
            'project': 'Project',
            
            
            'state': 'str',
            
            
            'attributeInfo': 'dict'
            
        }

        self.attributeMap = {
            
            'serialNumber': 'serialNumber',
            
            'stateDisplay': 'stateDisplay',
            
            'id': 'id',
            
            'platformId': 'platformId',
            
            'macAddress': 'macAddress',
            
            'smartAccountDeviceId': 'smartAccountDeviceId',
            
            'pnpSmartAccountId': 'pnpSmartAccountId',
            
            'pnpManaged': 'pnpManaged',
            
            'project': 'project',
            
            'state': 'state',
            
            'attributeInfo': 'attributeInfo'
            
        }       

        
        #serial number
        
        self.serialNumber = None # str
        
        
        self.stateDisplay = None # str
        
        #Smart Account Device Id
        
        self.id = None # str
        
        #platform id
        
        self.platformId = None # str
        
        #mac address
        
        self.macAddress = None # str
        
        #smart account device id
        
        self.smartAccountDeviceId = None # str
        
        #smart account id
        
        self.pnpSmartAccountId = None # str
        
        #pnp managed
        
        self.pnpManaged = None # bool
        
        #project contains this device
        
        self.project = None # Project
        
        #state
        
        self.state = None # str
        
        
        self.attributeInfo = None # dict
        
