#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class ZtdTemplateConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {

            'description': 'str',


            'id': 'str',


            'configId': 'str',


            'templateId': 'str',


            'configProperty': 'dict',


            'configIdTimestamp': 'str',


            'configPropertyTimestamp': 'str',


            'generate': 'bool',


            'name': 'str'
        }

        self.attributeMap = {

            'description': 'description',

            'id': 'id',

            'configId': 'configId',

            'templateId': 'templateId',

            'configProperty': 'configProperty',

            'configIdTimestamp': 'configIdTimestamp',

            'configPropertyTimestamp': 'configPropertyTimestamp',

            'generate': 'generate',

            'name': 'name'
        }


        #Template config description

        self.description = None # str

        #Template config ID

        self.id = None # str


        self.configId = None # str

        #Template ID

        self.templateId = None # str

        #Template varialble key-value pairs

        self.configProperty = None # dict


        self.configIdTimestamp = None # str


        self.configPropertyTimestamp = None # str

        #True to generate template

        self.generate = None # bool

        #Template config name

        self.name = None # str
