#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class ApplicationIpPortClassifierDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'protocol': 'str',
            
            
            'ipAddress': 'str',
            
            
            'ports': 'list[int]',
            
            
            'lowerPort': 'int',
            
            
            'upperPort': 'int',
            
            
            'subnetMask': 'int',
            
            
            'ipPorts': 'list[int]'
            
        }

        self.attributeMap = {
            
            'protocol': 'protocol',
            
            'ipAddress': 'ipAddress',
            
            'ports': 'ports',
            
            'lowerPort': 'lowerPort',
            
            'upperPort': 'upperPort',
            
            'subnetMask': 'subnetMask',
            
            'ipPorts': 'ipPorts'
            
        }       

        
        #Protocol of the application. Allowed values are tcp, udp, tcp/udp, ip or it could be empty. Values are case sensitive.
        
        self.protocol = None # str
        
        #IP address of the application.
        
        self.ipAddress = None # str
        
        #L4 Port numbers of the application.
        
        self.ports = None # list[int]
        
        #Lower Port of the Port range.
        
        self.lowerPort = None # int
        
        #Upper Port of the Port range.
        
        self.upperPort = None # int
        
        #Subnet mask. Defaults to 32
        
        self.subnetMask = None # int
        
        #L3 Protocol numbers of the application
        
        self.ipPorts = None # list[int]
        
