#!/usr/bin/env python
#pylint: skip-file
# This source code is licensed under the Apache license found in the
# LICENSE file in the root directory of this project.

class BandwidthProfileAssociatedPolicyScopeDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {

            'stale': 'bool',


            'policyScope': 'str'

        }

        self.attributeMap = {

            'stale': 'stale',

            'policyScope': 'policyScope'

        }


        #Flag indicating whether the BandwidthProfile has been updated since the last time its associated policies were provisioned

        self.stale = None # bool

        #Policy scope using this BandwidthProfile

        self.policyScope = None # str

