#!/usr/bin/env python
#pylint: skip-file
# This source code is licensed under the Apache license found in the
# LICENSE file in the root directory of this project.

class BandwidthProfileDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {

            'interfaceTrafficClassBandwidthSettingsList': 'list[InterfaceTrafficClassBandwidthSettingsDTO]',


            'bandwidthProfileAssociatedPolicyScopes': 'list[BandwidthProfileAssociatedPolicyScopeDTO]',


            'version': 'int',


            'name': 'str',


            'description': 'str',


            'defaultProfile': 'bool',


            'id': 'str',


            'lastUpdateTime': 'int',


            'createTime': 'int'

        }

        self.attributeMap = {

            'interfaceTrafficClassBandwidthSettingsList': 'interfaceTrafficClassBandwidthSettingsList',

            'bandwidthProfileAssociatedPolicyScopes': 'bandwidthProfileAssociatedPolicyScopes',

            'version': 'version',

            'name': 'name',

            'description': 'description',

            'defaultProfile': 'defaultProfile',

            'id': 'id',

            'lastUpdateTime': 'lastUpdateTime',

            'createTime': 'createTime'

        }


        #List of Traffic Class Bandwidth Settings for the different interface speeds supported

        self.interfaceTrafficClassBandwidthSettingsList = None # list[InterfaceTrafficClassBandwidthSettingsDTO]

        #read only list of policy scopes using the BandwidthProfile

        self.bandwidthProfileAssociatedPolicyScopes = None # list[BandwidthProfileAssociatedPolicyScopeDTO]

        #Incremental number representing the version of the BandwidthProfile

        self.version = None # int

        #unique name for the BandwidthProfile

        self.name = None # str

        #Description for the BandwidthProfile

        self.description = None # str

        #A flag to indicate if the BandwidthProfile is a default/user-defined one

        self.defaultProfile = None # bool

        #id

        self.id = None # str

        #lastUpdateTime

        self.lastUpdateTime = None # int

        #createTime

        self.createTime = None # int

