#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class ClassModelDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'name': 'str',
            
            
            'dscp': 'str',
            
            
            'priority': 'bool',
            
            
            'bandwidthPercentage': 'int',
            
            
            'admittedTrafficClasses': 'list[str]'
            
        }

        self.attributeMap = {
            
            'name': 'name',
            
            'dscp': 'dscp',
            
            'priority': 'priority',
            
            'bandwidthPercentage': 'bandwidthPercentage',
            
            'admittedTrafficClasses': 'admittedTrafficClasses'
            
        }       

        
        #
        
        self.name = None # str
        
        #Valid values are from 0 to 63 inclusive
        
        self.dscp = None # str
        
        #1 and Only 1 classModel in a given ServiceProviderProfile should have priority value as &#39;true&#39;
        
        self.priority = None # bool
        
        #Valid values are from 1 to 100 inclusive
        
        self.bandwidthPercentage = None # int
        
        #Valid values are broadcast-video, bulk-data, multimedia-conferencing, multimedia-streaming, network-control, ops-admin-mgmt, real-time-interactive, signaling, transactional-data, voip-telephony, best-effort, scavenger
        
        self.admittedTrafficClasses = None # list[str]
        
