#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class ServiceProviderProfileDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'description': 'str',
            
            
            'name': 'str',
            
            
            'interfaces': 'list[ServiceProviderProfileInterfaceDTO]',
            
            
            'defaultModel': 'bool',
            
            
            'modelType': 'str',
            
            
            'vendor': 'str',
            
            
            'currentVersion': 'int',
            
            
            'classModels': 'list[ClassModelDTO]',
            
            
            'id': 'str',
            
            
            'lastUpdateTime': 'int',
            
            
            'createTime': 'int'
            
        }

        self.attributeMap = {
            
            'description': 'description',
            
            'name': 'name',
            
            'interfaces': 'interfaces',
            
            'defaultModel': 'defaultModel',
            
            'modelType': 'modelType',
            
            'vendor': 'vendor',
            
            'currentVersion': 'currentVersion',
            
            'classModels': 'classModels',
            
            'id': 'id',
            
            'lastUpdateTime': 'lastUpdateTime',
            
            'createTime': 'createTime'
            
        }       

        
        
        self.description = None # str
        
        #unique name for the ServiceProviderProfile
        
        self.name = None # str
        
        
        self.interfaces = None # list[ServiceProviderProfileInterfaceDTO]
        
        #Read only attribute to indicate whether the ServiceProviderProfile is default(&#39;true&#39;) or custom(&#39;false&#39;)
        
        self.defaultModel = None # bool
        
        #Available options are: Three-Class, Four-Class, Five-Class, Six-Class, Eight-Class
        
        self.modelType = None # str
        
        
        self.vendor = None # str
        
        
        self.currentVersion = None # int
        
        #classModels list size should match the modelType
        
        self.classModels = None # list[ClassModelDTO]
        
        #id
        
        self.id = None # str
        
        #lastUpdateTime
        
        self.lastUpdateTime = None # int
        
        #createTime
        
        self.createTime = None # int
        
