#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class ScalableGroupDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'description': 'str',
            
            
            'createTime': 'int',
            
            
            'scalableGroupExternalHandle': 'str',
            
            
            'lastUpdateTime': 'int',
            
            
            'applications': 'list[ApplicationV2DTOBrief]',
            
            
            'applicationGroups': 'list[ApplicationGroupDTOBrief]',
            
            
            'parentScalableGroup': 'ScalableGroupBriefDTO',
            
            
            'identitySourceIpAddress': 'str',
            
            
            'identitySourceId': 'str',
            
            
            'identitySourceType': 'str',
            
            
            'name': 'str',
            
            
            'id': 'str',
            
            
            'state': 'str'
            
        }

        self.attributeMap = {
            
            'description': 'description',
            
            'createTime': 'createTime',
            
            'scalableGroupExternalHandle': 'scalableGroupExternalHandle',
            
            'lastUpdateTime': 'lastUpdateTime',
            
            'applications': 'applications',
            
            'applicationGroups': 'applicationGroups',
            
            'parentScalableGroup': 'parentScalableGroup',
            
            'identitySourceIpAddress': 'identitySourceIpAddress',
            
            'identitySourceId': 'identitySourceId',
            
            'identitySourceType': 'identitySourceType',
            
            'name': 'name',
            
            'id': 'id',
            
            'state': 'state'
            
        }       

        
        #description
        
        self.description = None # str
        
        #createTime
        
        self.createTime = None # int
        
        #scalableGroupExternalHandle
        
        self.scalableGroupExternalHandle = None # str
        
        #lastUpdateTime
        
        self.lastUpdateTime = None # int
        
        #applications that belong to the scalable group.
        
        self.applications = None # list[ApplicationV2DTOBrief]
        
        #applicationGroups that belong to the scalable group.
        
        self.applicationGroups = None # list[ApplicationGroupDTOBrief]
        
        #parentScalableGroup from which user, user groups are inherited.
        
        self.parentScalableGroup = None # ScalableGroupBriefDTO
        
        #identitySourceIpAddress
        
        self.identitySourceIpAddress = None # str
        
        #identitySourceId
        
        self.identitySourceId = None # str
        
        #identitySourceType
        
        self.identitySourceType = None # str
        
        #name
        
        self.name = None # str
        
        #id
        
        self.id = None # str
        
        #state
        
        self.state = None # str
        
