#!/usr/bin/env python
#pylint: skip-file
"""
AlarmApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os
import urllib.request, urllib.parse, urllib.error

from .models import *


class AlarmApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient



    def getAlarmWithFilter(self, **kwargs):
        """Retrieve Alarms

        Args:


        Returns: ListAlarmDTOResponse
        """

        allParams = []

        params = locals()
        for (key, val) in list(params['kwargs'].items()):
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getAlarmWithFilter" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/alarm'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'











        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)


        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ListAlarmDTOResponse')
        return responseObject




    def getAlarmCountWithFilter(self, **kwargs):
        """Retrieve Count of number of alarms

        Args:


        Returns: int
        """

        allParams = []

        params = locals()
        for (key, val) in list(params['kwargs'].items()):
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getAlarmCountWithFilter" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/alarm/count'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'











        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)


        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'CountResult')
        return responseObject




    def acknowledgeAlarm(self, **kwargs):
        """Acknowledge an Alarm by UUID

        Args:

            alertUUID, str: alertUUID (required)


            alarmDTO, AlarmDTO: alarmDTO (required)



        Returns: SuccessResult
        """

        allParams = ['alertUUID', 'alarmDTO']

        params = locals()
        for (key, val) in list(params['kwargs'].items()):
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method acknowledgeAlarm" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/alarm/{alertUUID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'






        if ('alertUUID' in params):
            replacement = str(self.apiClient.toPathValue(params['alertUUID']))
            replacement = urllib.parse.quote(replacement)
            resourcePath = resourcePath.replace('{' + 'alertUUID' + '}',
                                                replacement)





        if ('alarmDTO' in params):
            bodyParam = params['alarmDTO']


        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)


        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'SuccessResult')
        return responseObject
