#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class NetworkWideSettingsDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'netflow': 'NetflowSettingsDTO',
            
            
            'aaa': 'AAASettingsDTO',
            
            
            'dns': 'DNSSettingsDTO',
            
            
            'snmp': 'SNMPSettingsDTO',
            
            
            'dhcp': 'list[DHCPServerSettingsDTO]',
            
            
            'systemSettingsDTO': 'SystemSettingsDTO',
            
            
            'hubSiteDTO': 'list[HubSiteDTO]',
            
            
            'ipAddressPoolWrapperDTO': 'IpAddressPoolWrapperDTO',
            
            
            'errorHandleCondition': 'str',
            
            
            'ldap': 'LDAPSettingsDTO',
            
            
            'syslog': 'list[SyslogSettingsDTO]',
            
            
            'ntp': 'NTPSettingsDTO',
            
            
            'controllerNat': 'NATSettingsDTO',
            
            
            'ipPoolGlobalDTO': 'IpAddressGlobalDTO',
            
            
            'certifiedIOSRelease': 'list[CertifiedImageDTO]',
            
            
            'configurationType': 'str'
            
        }

        self.attributeMap = {
            
            'netflow': 'netflow',
            
            'aaa': 'aaa',
            
            'dns': 'dns',
            
            'snmp': 'snmp',
            
            'dhcp': 'dhcp',
            
            'systemSettingsDTO': 'systemSettingsDTO',
            
            'hubSiteDTO': 'hubSiteDTO',
            
            'ipAddressPoolWrapperDTO': 'ipAddressPoolWrapperDTO',
            
            'errorHandleCondition': 'errorHandleCondition',
            
            'ldap': 'ldap',
            
            'syslog': 'syslog',
            
            'ntp': 'ntp',
            
            'controllerNat': 'controllerNat',
            
            'ipPoolGlobalDTO': 'ipPoolGlobalDTO',
            
            'certifiedIOSRelease': 'certifiedIOSRelease',
            
            'configurationType': 'configurationType'
            
        }       

        
        
        self.netflow = None # NetflowSettingsDTO
        
        
        self.aaa = None # AAASettingsDTO
        
        
        self.dns = None # DNSSettingsDTO
        
        
        self.snmp = None # SNMPSettingsDTO
        
        
        self.dhcp = None # list[DHCPServerSettingsDTO]
        
        
        self.systemSettingsDTO = None # SystemSettingsDTO
        
        
        self.hubSiteDTO = None # list[HubSiteDTO]
        
        
        self.ipAddressPoolWrapperDTO = None # IpAddressPoolWrapperDTO
        
        
        self.errorHandleCondition = None # str
        
        
        self.ldap = None # LDAPSettingsDTO
        
        
        self.syslog = None # list[SyslogSettingsDTO]
        
        
        self.ntp = None # NTPSettingsDTO
        
        
        self.controllerNat = None # NATSettingsDTO
        
        
        self.ipPoolGlobalDTO = None # IpAddressGlobalDTO
        
        
        self.certifiedIOSRelease = None # list[CertifiedImageDTO]
        
        
        self.configurationType = None # str
        
