#!/usr/bin/env python
#pylint: skip-file
"""
SegmentApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os
import urllib.request, urllib.parse, urllib.error

from .models import *


class SegmentApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def getSegmentInfo(self, **kwargs):
        """list of segment info based on the policyTag

        Args:
            
            type, str: Type of segment (required)
            
            
            policyTag, str: Policy tag (required)
            
            
        
        Returns: SegmentResult
        """

        allParams = ['type', 'policyTag']

        params = locals()
        for (key, val) in list(params['kwargs'].items()):
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getSegmentInfo" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/segment'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        headerParams['Accept'] = 'application/json'
        headerParams['Content-Type'] = 'application/json'

        
        if ('type' in params):
            queryParams['type'] = self.apiClient.toPathValue(params['type'])
        
        if ('policyTag' in params):
            queryParams['policyTag'] = self.apiClient.toPathValue(params['policyTag'])
        

        

        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'SegmentResult')
        return responseObject
        
        
        
    


