#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class NetworkDeviceReachabilityInfoNIO(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'snmpCommunity': 'str',
            
            
            'mgmtIp': 'str',
            
            
            'protocolList': 'str',
            
            
            'protocolUsed': 'str',
            
            
            'discoveryStartTime': 'str',
            
            
            'enablePassword': 'str',
            
            
            'userName': 'str',
            
            
            'password': 'str',
            
            
            'discoveryId': 'str',
            
            
            'id': 'str',
            
            
            'reachabilityFailureReason': 'str',
            
            
            'reachabilityStatus': 'str',
            
            
            'attributeInfo': 'object'
            
        }

        self.attributeMap = {
            
            'snmpCommunity': 'snmpCommunity',
            
            'mgmtIp': 'mgmtIp',
            
            'protocolList': 'protocolList',
            
            'protocolUsed': 'protocolUsed',
            
            'discoveryStartTime': 'discoveryStartTime',
            
            'enablePassword': 'enablePassword',
            
            'userName': 'userName',
            
            'password': 'password',
            
            'discoveryId': 'discoveryId',
            
            'id': 'id',
            
            'reachabilityFailureReason': 'reachabilityFailureReason',
            
            'reachabilityStatus': 'reachabilityStatus',
            
            'attributeInfo': 'attributeInfo'
            
        }       

        
        #SNMP community used for device connectivity
        
        self.snmpCommunity = None # str
        
        #IP address of the device
        
        self.mgmtIp = None # str
        
        #Protocol order given for discovery
        
        self.protocolList = None # str
        
        #Protocol used for device discovery
        
        self.protocolUsed = None # str
        
        #Time when the discovery was started
        
        self.discoveryStartTime = None # str
        
        #CLI enable password used for device connectivity
        
        self.enablePassword = None # str
        
        #CLI username used for device connectivity
        
        self.userName = None # str
        
        #CLI password used for device connectivity
        
        self.password = None # str
        
        #ID of discovery thorugh which device was discovered
        
        self.discoveryId = None # str
        
        #Unique identifier for reachability-info
        
        self.id = None # str
        
        #Reason for failure if the device is not discovered successfully
        
        self.reachabilityFailureReason = None # str
        
        #Reachability status of the device as Reachable / Unreachable
        
        self.reachabilityStatus = None # str
        
        
        self.attributeInfo = None # object
        
