#!/usr/bin/env python
#pylint: skip-file
# This source code is licensed under the Apache license found in the
# LICENSE file in the root directory of this project.

class SiteList(object):
    """Generated manually to emulate the code that would be generated by swagger"""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """

        self.swaggerTypes = {
            'siteList': 'list[SiteInfo]'
        }

        self.attributeMap = {
            'siteList': 'siteList'
        }

        self.siteList = None # list[SiteInfo]
