#!/usr/bin/env python
#pylint: skip-file
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class ScheduleInfoOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'startTime': 'date-time',
            
            
            'endTime': 'date-time',
            
            
            'description': 'str',
            
            
            'origin': 'str',
            
            
            'taskId': 'str',
            
            
            'operation': 'str',
            
            
            'groupName': 'str',
            
            
            'prevTime': 'date-time',
            
            
            'nextTime': 'date-time',
            
            
            'scheduledWorkSpecId': 'str'
            
        }

        self.attributeMap = {
            
            'startTime': 'startTime',
            
            'endTime': 'endTime',
            
            'description': 'description',
            
            'origin': 'origin',
            
            'taskId': 'taskId',
            
            'operation': 'operation',
            
            'groupName': 'groupName',
            
            'prevTime': 'prevTime',
            
            'nextTime': 'nextTime',
            
            'scheduledWorkSpecId': 'scheduledWorkSpecId'
            
        }       

        
        #The time at which the trigger should first fire. If the schedule has fired and will not fire again, this value will be null
        
        self.startTime = None # date-time
        
        #The time at which the trigger should quit repeating
        
        self.endTime = None # date-time
        
        #Simple description to be shown to end-users
        
        self.description = None # str
        
        #Contextual field used to identify work spcifications originating from the same source
        
        self.origin = None # str
        
        #UUID of the Task
        
        self.taskId = None # str
        
        #Contextual field used by the service to identify an operation
        
        self.operation = None # str
        
        #A grouping name that can be specified by the service to allow for filtered work spec retrieval
        
        self.groupName = None # str
        
        #The previous time at which the trigger fired. If the trigger has not yet fired, null will be returned
        
        self.prevTime = None # date-time
        
        #The next time at which the trigger should fire
        
        self.nextTime = None # date-time
        
        #UUID of the ScheduledWorkSpec associated with the scheduled task
        
        self.scheduledWorkSpecId = None # str
        
